In [2]:
import numpy as np 
scores = [89,56.34, 76,89, 98]
first_arr =np.array(scores)
print(first_arr)

[ 89.    56.34  76.    89.    98.  ]


In [3]:
first_arr(0)

TypeError: 'numpy.ndarray' object is not callable

In [4]:
first_arr[0]

89.0

In [5]:
first_arr.shape

(5,)

In [6]:
tarr=[[11,22,33],[44,55,66],[77,88,99]]
ta=np.array(tarr)

In [7]:
ta

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [8]:
ta.shape

(3, 3)

In [9]:
np.ones(7)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
np.zeros(7)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
format(ta)

'[[11 22 33]\n [44 55 66]\n [77 88 99]]'

In [12]:
ta

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [13]:
ta[:2]

array([[11, 22, 33],
       [44, 55, 66]])

In [14]:
ta[1:2]

array([[44, 55, 66]])

In [15]:
ta[1:2,1]

array([55])

In [16]:
ta[1:2,:1]

array([[44]])

In [17]:
ta[1:2,:2]

array([[44, 55]])

In [18]:
ta[1:2,:3]

array([[44, 55, 66]])

In [19]:
ta[1:2,3:]

array([], shape=(1, 0), dtype=int32)

In [27]:
ta[:2,:2]

array([[11, 22],
       [44, 55]])

In [28]:
from numpy import random
rn=random.rand(2,3)
rn


array([[ 0.70031241,  0.77033835,  0.15619739],
       [ 0.82116458,  0.59696519,  0.40480208]])

In [36]:
w=[2,3,4,5]
w1=np.array(w)
print(w1)
#print(w1.shape)
w2=w1.T
print(w2)
#print(w1.T.shape)

[2 3 4 5]
[2 3 4 5]


In [38]:
w1[0]

2

In [39]:
w

[2, 3, 4, 5]

In [43]:
ri=[0.5,6.7,8.6,2.3]
x=np.array(ri)
x

array([ 0.5,  6.7,  8.6,  2.3])

In [44]:
X=x.T
X

array([ 0.5,  6.7,  8.6,  2.3])

In [45]:
X.shape

(4,)

In [46]:
w*X

array([  1. ,  20.1,  34.4,  11.5])

In [47]:
w

[2, 3, 4, 5]

In [48]:
W=w.reshape(4,1)
W

AttributeError: 'list' object has no attribute 'reshape'

In [49]:
w

[2, 3, 4, 5]

In [50]:
X

array([ 0.5,  6.7,  8.6,  2.3])

In [51]:
W1=np.mat(w)
W1

matrix([[2, 3, 4, 5]])

In [52]:
W2=W1.reshape(4,1)
W2

matrix([[2],
        [3],
        [4],
        [5]])

In [53]:
X1=np.mat(X)
X2=X1.reshape(1,4)
X2

matrix([[ 0.5,  6.7,  8.6,  2.3]])

In [54]:
W2.shape

(4, 1)

In [55]:
X2.shape

(1, 4)

In [56]:
W2*X2

matrix([[  1. ,  13.4,  17.2,   4.6],
        [  1.5,  20.1,  25.8,   6.9],
        [  2. ,  26.8,  34.4,   9.2],
        [  2.5,  33.5,  43. ,  11.5]])

In [57]:
W2

matrix([[2],
        [3],
        [4],
        [5]])

In [58]:
X2

matrix([[ 0.5,  6.7,  8.6,  2.3]])

In [59]:
W2+X2

matrix([[  2.5,   8.7,  10.6,   4.3],
        [  3.5,   9.7,  11.6,   5.3],
        [  4.5,  10.7,  12.6,   6.3],
        [  5.5,  11.7,  13.6,   7.3]])

In [60]:
X

array([ 0.5,  6.7,  8.6,  2.3])

In [61]:
W2

matrix([[2],
        [3],
        [4],
        [5]])

In [62]:
X*W2

matrix([[ 67.]])

In [ ]:
#McCulloch Pitts Neuron Model for AND function
import numpy as np
Threshold=2
bias=0
W=[1,1]
print('Enter Inputs for AND function')
i1=int(input('Enter first input\n'))
i2=int(input('Enter Second input\n'))
X=[i1,i2]
X1=np.mat(X)
W1=np.mat(W)
W2=W1.reshape(2,1)
print(X1)
print(W2)
print(X1.shape)
print(W2.shape)
#W2=W1.reshape(2,1)
Net=X1*W2+bias
print(Net)
if Net>=Threshold:
    print('Output=',1)
else:
    print('Output=',0)


In [ ]:
#McCulloch Pitts Neuron Model for AND function
import numpy as np
Threshold=2
bias=0
W=[1,1]
print('Enter Inputs for AND function')
i1=int(input('Enter first input\n'))
i2=int(input('Enter Second input\n'))
X=[i1,i2]
X1=np.mat(X)
W1=np.mat(W)
W2=W1.reshape(2,1)
print(X1)
print(W2)
print(X1.shape)
print(W2.shape)
#W2=W1.reshape(2,1)
Net=X1*W2+bias
print(Net)
if Net>=Threshold:
    print('Output=',1)
else:
    print('Output=',0)
